#! /bin/python

urls=[
# 'https://cdn.aayus.me/tedx/press/Kayal_0023.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0029.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0030.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0036.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0037.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0038.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0045.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0066.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0068.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0069.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0070.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0071.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0072.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0073.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0074.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0075.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0088.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0089.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0098.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0111.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0115.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0119.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0126.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0140.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0142.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0145.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0147.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0148.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0150.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0151.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0152.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0153.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0155.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0156.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0157.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0160.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0161.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0162.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0163.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0164.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0166.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0168.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0172.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0173.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0175.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0177.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0178.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0187.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0188.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0189.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0192.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0201.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0209.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0213.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0214.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0237.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0238.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0242.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0251.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0258.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0259.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0260.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0264.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0266.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0270.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0286.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0288.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0293.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0297.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0308.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0310.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0312.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0317.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0320.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0323.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0325.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0328.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0331.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0335.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0340.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0358.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0361.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0364.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0369.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0373.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0374.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0388.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0389.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0390.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0397.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0398.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0412.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0413.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0421.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0426.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0427.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0428.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0429.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0433.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0435.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0436.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0437.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0438.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0439.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0443.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0458.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0459.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0460.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0461.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0462.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0463.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0464.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0466.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0467.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0468.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0469.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0470.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0471.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0473.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0478.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0482.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0483.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0489.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0494.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0499.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0503.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_0504.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_2007.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_2023.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_20241215_173711.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_20241215_180830.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_20241215_182236.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_20241215_182647_edit_60644877376968.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_20241215_183204.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_20241215_183539.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_20241215_183735.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_20241215_195042.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_20241215_200306.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_20241215_200309.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_2048.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_2049.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_9940.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_9942.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_9943.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_9945.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_9956.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_9957.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_9958.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_9964.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_9965.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_9968.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_9971.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_9978.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_9981.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_9988.jpg',
# 'https://cdn.aayus.me/tedx/press/Kayal_9989.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0218.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0219.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0220.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0221.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0224.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0225.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0226.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0227.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0228.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0229.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0230.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0231.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0232.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0235.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0238.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0239.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0240.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0243.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0245.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0246.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0247.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0248.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0251.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0253.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0254.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0255.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0256.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0262.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0263.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0264.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0265.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0267.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0269.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0272.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0273.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0274.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0276.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0277.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0280.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0281.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0282.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0283.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0285.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0287.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0288.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0290.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0291.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0292.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0293.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0294.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0295.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0296.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0297.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0298.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0300.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0301.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0302.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0303.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0305.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0306.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0307.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0308.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0311.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0314.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0316.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0317.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0318.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0320.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0321.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0322.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0323.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0324.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0325.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0326.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0328.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0330.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0331.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0332.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0333.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0334.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0348.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0350.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0351.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0352.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0353.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0354.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0355.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0359.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0362.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0363.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0364.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0369.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0370.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0371.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0373.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0375.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0376.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0379.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0385.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0386.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0387.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0389.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0390.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0391.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0392.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0394.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0395.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0396.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0397.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0398.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0400.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0403.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0404.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0405.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0406.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0409.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0410.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0411.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0412.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0413.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0415.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0416.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0417.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0418.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0419.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0420.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0422.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0424.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0425.jpg',
# 'https://cdn.aayus.me/tedx/press/Press_0426.jpg',
# 'https://cdn.aayus.me/tedx/press/Rayed_0032.jpg',
# 'https://cdn.aayus.me/tedx/press/Rayed_0052.jpg',
# 'https://cdn.aayus.me/tedx/press/Rayed_0054.jpg',
# 'https://cdn.aayus.me/tedx/press/Rayed_0058.jpg',
# 'https://cdn.aayus.me/tedx/press/Rayed_0059.jpg',
# 'https://cdn.aayus.me/tedx/press/Rayed_0062.jpg',
# 'https://cdn.aayus.me/tedx/press/Rayed_0064.jpg',
# 'https://cdn.aayus.me/tedx/press/Rayed_0079.jpg',
# 'https://cdn.aayus.me/tedx/press/Rayed_0080.jpg',
# 'https://cdn.aayus.me/tedx/press/Rayed_0084.jpg',
# 'https://cdn.aayus.me/tedx/press/Rayed_0085.jpg',
# 'https://cdn.aayus.me/tedx/press/Rayed_0086.jpg',
# 'https://cdn.aayus.me/tedx/press/Rayed_0090.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6763.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6765.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6766.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6767.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6768.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6769(1).jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6769.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6770.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6771.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6772.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6773.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6774.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6775.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6776.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6777.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6780.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6781.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6782.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6783.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6785.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6786.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6787.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6788.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6789.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6790.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6791.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6792.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6793.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6794.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6795.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6796.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6797.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6811.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6812.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6818.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6819.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6820(1).jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6820.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6821(1).jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6821.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6822.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6823.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6824.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6825.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6826.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6827.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6828.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6829.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6830.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6831.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6832.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6833.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6834.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6835.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6836.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6837.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6838.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6839.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6840.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6841.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6842.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6843.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6844.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6845.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6846.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6847.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6848.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6849.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6850.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6851.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6852.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6853.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6854.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6855.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6856.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6857.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6858.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6859.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6860.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6861.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6862.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6863.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6864.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6865.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6866.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6867.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6868.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6869.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6870.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6871.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6872.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6873.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6874.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6875.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6876.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6877.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6878.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6879.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6880.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6881.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6882.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6883.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6884.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6885.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6886.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6887.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6888.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6889.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6890.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6891.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6892.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6893.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6894.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6895.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6896.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6897.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6898.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6899.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6900.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6901.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6902.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6903.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6904.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6905.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6906.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6907.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6908.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6909.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6910.jpg',
'https://cdn.aayus.me/tedx/press/Swastik_6911.jpg',
]


gallery_images = []

for index, url in enumerate(urls, start=1):
    filename = url.split("/")[-1]
    gallery_images.append({
        "id": 299+index,
        "url": url,
        "thumbnail": f"https://cdn.aayus.me/tedx/press/thumbs/{filename}",
        "alt": f"{filename}"
    })

import json
print(json.dumps(gallery_images, indent=4))
